services:
  db:
    image: mysql:latest
    container_name: dictionary-api-db
    environment:
      - MYSQL_ROOT_PASSWORD=0123456789
    ports: 
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
  backend:
    build:
      context: ./backend
    container_name: dictionary-api-backend
    ports:
      - 80:80
    volumes:
      - ./backend/app:/code/app
